version: '3.3'
services:
    ia-vue:
        build: './vue-3'
        container_name: ia-vue
        volumes:
            - ./vue-3:/app
            - /app/node_modules
        ports:
            - '8080:8080'
        image: 'ia-vue:dev'
    ia-flask:
        build: './flask'
        restart: unless-stopped
        container_name: ia-flask
        environment:
          - PYTHONUNBUFFERED=1
        volumes:
            - ./flask:/working_dir
        ports:
            - '5000:5000'
        image: 'ia-flask:dev'
    ia-postgres:
        image: postgres:11.5
        container_name: ia-postgres
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER=ia
          - POSTGRES_PASSWORD=change_for_prod
          - POSTGRES_DB=ia
    docker-airflow:
        container_name: ia-airflow
        ports:
          - '8081:8080'
        image: puckel/docker-airflow:1.10.4
        environment:
          - LOAD_EX=y
